name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Nice work! You just added your first issue in this repository! Hang in there, I`ll get back to you ASAP! '
        pr-message: 'Nice work! You just added your first pul request in this repository! Hang in there, I`ll get back to you ASAP! '
